module Xkbcommon.Xkbcommon where

{- Flags for keymap compilation.
    /** Do not apply any flags. */
    XKB_KEYMAP_COMPILE_NO_FLAGS = 0
-}
{{ enum
    xkb_keymap_compile_flags,
    XKB_KEYMAP_COMPILE_NO_FLAGS
}}

{- The possible keymap formats.
    /** The current/classic XKB text format, as generated by xkbcomp -xkb. */
    XKB_KEYMAP_FORMAT_TEXT_V1 = 1
 -}
{{ enum
    xkb_keymap_format,
    XKB_KEYMAP_FORMAT_TEXT_V1
}}
